### PR TITLE
Remove @ComponentScan from auto configured classes.

### PR DESCRIPTION
**Pull request by ihrigb**
This removes the `@ComponentScan` annotation from the configuration class, since this is not a good practice in external librarys/components.
The Service Broker now is configured via auto configuration.

Also adds copyright headers to all touched files.

### CODE REVIEW

**Comment by ihrigb** [comment]
Any news on this?

**Comment by scottfrederick** [comment]
@ihrigb This PR still contains a lot of unnecessary re-formatting of code, which obscures the functional changes and makes the PR difficult to review. I understand that you are trying to apply the Spring Cloud formatter, but please do not re-format code for the sake of re-formatting in PRs. 

Otherwise, I need to review the functional change for backward compatibility before accepting.

**Comment by ihrigb** [comment]
I just conformed to Spring's conventions. There is not too much reformatting, also actual changes are shown in stronger colors.
This project should be in line with the conventions, which are claimed in its readme, and contributors should not be blamed for adhering them.

**Comment by scottfrederick** [comment]
@ihrigb As part of an effort to update this project and release a 2.0.0 release with new features, the spirit of your changes here have been incorporated into a separate [auto-configuration](https://github.com/spring-cloud/spring-cloud-cloudfoundry-service-broker/tree/master/spring-cloud-open-service-broker-autoconfigure/src/main/java/org/springframework/cloud/servicebroker/autoconfigure/web) subproject. Your `@author` tag has been maintained there to keep the proper attribution. I'm closing this PR, as we don't want to introduce this backward-incompatible change to the 1.0.x versions.

**Pull request closed without merging**
