### PR TITLE
Add method attached JSON schemas on service plans

### PR DESCRIPTION
**Pull request by Samze**
Services API Tracker story [#144874487](https://www.pivotaltracker.com/story/show/146604349)

## Why

The Open Service Broker API is [proposing](https://github.com/openservicebrokerapi/servicebroker/issues/59) allowing brokers to define JSON schema for their configuration parameters. This will allow tooling to validate parameters and UIs to auto generate forms.

Schemas are to be defined as part of the catalog on a plan and support create/update parameters on a service instance and create parameters on a service binding (update does not exist yet).

The updated spec can be found [here](https://github.com/avade/servicebroker/blob/method-attached-schemas/spec.md#schema-object).

Example of what a new catalog with schemas will look like:
```
    "plans": [{
      "name": "fake-plan-1",
      "id": "d3031751-XXXX-XXXX-XXXX-a42377d3320e",
      "description": "Shared fake Server, 5tb persistent disk, 40 max concurrent connections",
      "schemas": {
        "service_instance": {
          "create": {
            "parameters": {
              "$schema": "http://json-schema.org/draft-04/schema#",
              "type": "object",
              "properties": {
                "billing-account": {
                  "description": "Billing account number used to charge use of shared fake server.",
                  "type": "string"
                }
              }
            }
          },
          "update": {
            "parameters": {
              "$schema": "http://json-schema.org/draft-04/schema#",
              "type": "object",
              "properties": {
                "billing-account": {
                  "description": "Billing account number used to charge use of shared fake server.",
                  "type": "string"
                }
              }
            }
          }
        },
        "service_binding": {
          "create": {
            "parameters": {
              "$schema": "http://json-schema.org/draft-04/schema#",
              "type": "object",
              "properties": {
                "super_credential": {
                  "description": "Do you want a super credential in your life? I bet.",
                  "type": "boolean"
                }
              }
            }
          }
        }
      }
    }
```

## What

* Add model objects on a catalog plan that support adding method attached schemas.
* Added integration test for schemas.

You can see an example of a Spring boot broker defining schemas with the new model objects [here](https://github.com/Samze/spring-cloud-schema-broker/blob/master/src/main/java/broker/CatalogConfig.java#L57-L60).

## Questions/Feedback
1. The number of objects the broker authors must create to attach a schema is quite a lot. e.g. `Schemas` `ServiceInstanceSchemas` `MethodSchemas`. However this directly reflects the JSON and will lead to flexibility in the future when the spec gets extended e.g. support more methods or support for response schemas.
1. I have added the new model objects in the model folder as per current convention. This is quite crowded, would you prefer them in a separate `model.schemas` package? 
1. To add schemas to the plan I have followed the existing convention of adding a new constructor. I assume this is to allow backward compatibility?
1. After defining where to attach the schema the broker author must provide a Map<String, Object> of their schema (under parameters). Broker authors then have a choice of ways to ad their JSON schema. See examples [here](https://github.com/Samze/spring-cloud-schema-broker/blob/master/src/main/java/broker/CatalogConfig.java#L52-L89)

This is still only a proposed change and while it is expected to make it into v2.13 of the OSBAPI spec this is not certain. We are currently implementing this in CC as an experimental feature. We should consider what the impact would be should this feature change. Is there a way to release a beta of this package?

Any other feedback/thoughts welcome!

Thanks,
Sam

cc: @matthewmcnew

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@Samze Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-cloudfoundry-service-broker&pullRequestId=36)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-cloudfoundry-service-broker&pullRequestId=36) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by Samze** [comment]
Signed the CLA

**Comment by pivotal-issuemaster** [comment]
@Samze Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-cloudfoundry-service-broker&pullRequestId=36)!

**Comment by scottfrederick** [comment]
@Samze This looks good, I'll merge it as-is.

**Comment by scottfrederick** [comment]
@Samze some responses to your questions? 

> 1. The number of objects the broker authors must create to attach a schema is quite a lot. e.g. Schemas ServiceInstanceSchemas MethodSchemas. However this directly reflects the JSON ....

Specifying the service offering and plan details does get to be rather verbose, but generally does reflect the structure of the JSON. What you've added is consistent with the current design. 

> 2. I have added the new model objects in the model folder as per current convention. This is quite crowded, would you prefer them in a separate model.schemas package?

It would be good to refactor this package to introduce another layer of packaging, but this would break backward compatibility. I'll add an issue to do this in a future minor release. 

> 3. To add schemas to the plan I have followed the existing convention of adding a new constructor. I assume this is to allow backward compatibility?

Correct, the constructors are for backward compatibility and have been added as new optional fields have been added to the `Plan` model. We've talked about introducing a [builder pattern](https://en.wikipedia.org/wiki/Builder_pattern) as an alternative to constructor explosion.

**Comment by Samze** [comment]
Thanks for your response and merging @scottfrederick!

**Pull request merged**
